name: integration test
on:
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci
      - run: npm run build
      - run: npm prune --production
      - uses: actions/upload-artifact@v2
        with:
          name: action
          path: ./

  run:
    runs-on: ubuntu-latest
    needs: 'build'
    strategy:
      matrix:
        num: [1, 2, 3, 4, 5, 6]
    outputs:
      result: ${{ steps.critical-section.outputs.result }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: action

      - name: run the action
        uses: ./

      - id: critical-section
        name: critical section
        run: |
          sleep 1
          echo "::set-output name=result::${{ matrix.num }}"

  validation:
    runs-on: ubuntu-latest
    needs: 'run'
    steps:
      - run: echo TODO
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
