name: test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      - run: npm ci
      - run: npm run build
      - run: npm test
